#Templates :
#todo define finale file_name : {AssetName_Version}
Version : "{Version}"
AssetFileName : "{AssetName}__{Task}__{Subtask}_$Version.{ext}"
Project : "D:/Prod/03_WORK_PIPE/01_ASSET_3D"
AssetPath : "{AssetType}/{AssetName}"
FileFolder : "{AssetType}/{AssetName}/{Task}/{Subtask}/$Version/" #path to the folder
AssetFilePath : "{AssetType}/{AssetName}/{Task}/{Subtask}/$Version/$AssetFileName" #path to the asset file
Workspace : "$FileFolder"
Render : "$Workspace/Render/{AssetName}__{Task}__{Subtask}_$Version"
Cache : "$Workspace/Cache"
Textures : "$Workspace/Textures"
Flip : "$Workspace/flip"
Publish : "{AssetType}/{AssetName}/{Task}/{Subtask}/Out"
